### ISSUE TITLE
Can't 'configure' menu or calendar on taskbar

### ISSUE THREAD

**Issue by anothernumber** [linuxmint/cinnamon#10070]
```
Kernel: 4.15.0-142-generic x86_64 bits: 64 compiler: gcc 
  v: 7.5.0 Desktop: Cinnamon 4.4.8 Distro: Linux Mint 19.3 Tricia 
  base: Ubuntu 18.04 bionic 

Machine:
  Type: Desktop Mobo: Micro-Star model: X470 GAMING PRO CARBON (MS-7B78) 
  v: 1.0 serial: <filter> UEFI: American Megatrends v: 2.80 date: 03/06/2019 
CPU:
  Topology: 8-Core model: AMD Ryzen 7 2700X bits: 64 type: MT MCP arch: Zen+ 
  rev: 2 L2 cache: 4096 KiB 
  flags: lm nx pae sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm 
  bogomips: 118385 
  Speed: 1886 MHz min/max: 2200/3700 MHz Core speeds (MHz): 1: 1983 2: 1887 
  3: 1964 4: 2135 5: 1867 6: 2072 7: 2074 8: 4148 9: 1935 10: 2140 11: 1845 
  12: 1907 13: 2076 14: 4150 15: 2197 16: 1960 
Graphics:
  Device-1: AMD Ellesmere [Radeon RX 470/480/570/570X/580/580X] 

 Display: x11 server: X.Org 1.19.6 driver: amdgpu,ati 
  unloaded: fbdev,modesetting,radeon,vesa resolution: 1920x1080~60Hz 
  OpenGL: renderer: Radeon RX 580 Series (POLARIS10 DRM 3.23.0 
  4.15.0-142-generic LLVM 10.0.0) 
  v: 4.6 Mesa 20.0.8 direct render: Yes 

Icon Theme : Mint-Y
```

 

**Issue**
For a few months now I've been unable to 'configure' the Menu, Calendar, or Places Center applets if I right-click the icon on the taskbar and press configure. Nothing happens. They all work normally otherwise - its just that right-click configure option doesn't work.

**Steps to reproduce**
Right-click on mouse and select 'configure'

**Expected behaviour**
Opens configuration menu

**Other information**
**~$ xlet-settings applet menu@cinnamon.org**
Traceback (most recent call last):
  File "/usr/share/cinnamon/cinnamon-settings/xlet-settings.py", line 49, in <module>
    class XLETSettingsButton(Button):
NameError: name 'Button' is not defined

**_File "/usr/share/cinnamon/cinnamon-settings/xlet-settings.py", lines 49 to 57**
class XLETSettingsButton(Button):
    def __init__(self, info, uuid, instance_id):
        super(XLETSettingsButton, self).__init__(info["description"])
        self.uuid = uuid
        self.instance_id = instance_id
        self.xletCallback = str(info["callback"])

    def on_activated(self):
        proxy.activateCallback('(sss)', self.xletCallback, self.uuid, self.instance_id)_

**Configuration info, if applicable**
The above error comes up with all 3 icons that won't 'configure'. (menu@cinnamon.org, placesCenter@scollins[ver 2.1] and calendar@cinnamon.org)

As the bug relates to an applet/extension I am unable to press 'configure' to get any further info.

```

python --version
Python 2.7.17



**python2 --version**
Python 2.7.17



**python3 --version**
Python 3.6.9



**which python**
/usr/bin/python

``
I've tried uninstalling and reinstalling all affected applets. This doesn't change anything. 
I've tried changing themes. This doesn't change anything.
Thank you in advance.
