### ISSUE TITLE
Firefox window has visible border

### ISSUE THREAD

**Issue by pn-santos** [linuxmint/cinnamon#10588]
```
 * Cinnamon version: Cinnamon 5.2.7
 * Distribution: Mint 20.3 (u[graded from clean install of 20.2)
 * Graphics hardware *and* driver used:
       Device-1: Intel UHD Graphics 630 
           vendor: Dell 
           driver: i915 
           v: kernel 
       Device-2: NVIDIA TU117M [GeForce GTX 1650 Mobile / Max-Q] 
           vendor: Hewlett-Packard 
           driver: nvidia 
           v: 495.46
       Display: 
           server: X.Org 1.20.13 
           driver: modesetting,nvidia 
           unloaded: fbdev,nouveau,vesa 
           resolution: 3840x2160~60Hz 
       OpenGL: 
           renderer: Mesa Intel UHD Graphics 630 (CFL GT2) 
           v: 4.6 Mesa 21.0.3 
           direct render: Yes
 * 64 bit
 ```

**Issue**

Firefox window is surrounded by a noticeable line. Below is an example of firefox vs chrome:

![firefox-border](https://user-images.githubusercontent.com/23340138/148639320-3303fb33-2562-43bb-9a57-6a7fa18a83b8.png)

The top of the widow is expecially "thick", and it doesn't go away even when window is maximized.

**Steps to reproduce**

I did 20.3 -> 20.3 upgrade but it might be unrelated, and also present in a 20.3 clean install.

Theme Settings:
- Windows borders: Mint-Y
- Icons / Controls / Desktop: Mint-Y-Dark

**Expected behaviour**

No window border

**Other information**
