### ISSUE TITLE
support for protocol https://github.com/flatpak/xdg-desktop-portal/blob/main/data/org.freedesktop.portal.Settings.xml#L34

### ISSUE THREAD

**Issue by olegStreejak** [linuxmint/cinnamon#10745]
```
Cinnamon 5.2.7
Mint 20.3
Graphics:
  Device-1: AMD Lucienne driver: amdgpu v: kernel
  Display: x11 server: X.Org 1.20.13 driver: loaded: amdgpu
    unloaded: modesetting resolution: 1920x1080~60Hz
  OpenGL: renderer: AMD RENOIR (DRM 3.41.0 5.13.0-39-generic LLVM 12.0.0)
    v: 4.6 Mesa 21.2.6
System:
  Host: ryzen5-5500u Kernel: 5.13.0-39-generic x86_64 bits: 64
    Desktop: Cinnamon 5.2.7 Distro: Linux Mint 20.3 Una
 ```

Hello,
in the latest telegram desktop the setting for auto-switching for light or dark depending on the system setting just disaapear and it stopped auto-switch also. I asked for help it the appropriate telegram beta channel, and they (suppose the developer) advised me to ask Cinnamon developers:

```
Me (Олег):
#bug beta 3.6.3 Linux - auto switch light/dark mode according with system settings
disappeared from advanced settings. Used it for ages but since that beta - only
instant switch at the top menu is available. Please let that setting be back!

𝙼𝚛. 𝙱𝚘𝚠𝚕𝚎𝚛 𝙷𝚊𝚝, [15.04.2022 10:42]
[В ответ на Олег]
Hi, you need to update your DE for the setting to reappear. KDE 5.24 or GNOME 42.

Олег, [15.04.2022 11:04]
[В ответ на 𝙼𝚛. 𝙱𝚘𝚠𝚕𝚎𝚛 𝙷𝚊𝚝]
thank you for reply. I'm on the latest linuxmint w/ cinnamon desktop. Up to the previous beta it wаs visible

𝙼𝚛. 𝙱𝚘𝚠𝚕𝚎𝚛 𝙷𝚊𝚝, [15.04.2022 11:05]
[В ответ на Олег]
You have to request Cinnamon developers to support this protocol
https://github.com/flatpak/xdg-desktop-portal/blob/main/data/org.freedesktop.portal.Settings.xml#L34

N 🍿, [15.04.2022 11:20]
[В ответ на 𝙼𝚛. 𝙱𝚘𝚠𝚕𝚎𝚛 𝙷𝚊𝚝]
Can't there be both ? And isn't gnome 42 too recent for a requirement ?

𝙼𝚛. 𝙱𝚘𝚠𝚕𝚎𝚛 𝙷𝚊𝚝, [15.04.2022 11:25]
well, the protocol is requirement, not gnome 42

𝙼𝚛. 𝙱𝚘𝚠𝚕𝚎𝚛 𝙷𝚊𝚝, [15.04.2022 11:26]
I don't want to have both, it was an ugly hack with code for every DE

𝙼𝚛. 𝙱𝚘𝚠𝚕𝚎𝚛 𝙷𝚊𝚝, [15.04.2022 11:26]
Based on theme name parsing
```
is that possible?
Thank you in advance for your reply
