### ISSUE TITLE
Switching workspaces programmatically

### ISSUE THREAD

**Issue by mehmetgunacti** [linuxmint/cinnamon#11030]
```
System: LM 21 64-bit
  Kernel: 5.15.0-43-generic x86_64 bits: 64 compiler: gcc v: 11.2.0 Desktop: Cinnamon 5.4.9
    tk: GTK 3.24.33 wm: Mutter dm: LightDM Distro: Linux Mint 21 Vanessa base: Ubuntu 22.04 jammy
Graphics:
  Device-1: Intel 3rd Gen Core processor Graphics vendor: Samsung Co driver: i915 v: kernel ports:
    active: HDMI-A-1 off: LVDS-1 empty: DP-1,VGA-1 bus-ID: 00:02.0 chip-ID: 8086:0166
  Device-2: AMD Thames [Radeon HD 7500M/7600M Series] vendor: Samsung Co driver: radeon
    v: kernel pcie: speed: 2.5 GT/s lanes: 16 bus-ID: 01:00.0 chip-ID: 1002:6840
  Device-3: Microdia WebCam SC-13HDL12639P type: USB driver: uvcvideo bus-ID: 1-1.4:5
    chip-ID: 0c45:c35a
  Display: x11 server: X.Org v: 1.21.1.3 driver: X: loaded: ati,modesetting,radeon
    unloaded: fbdev,vesa gpu: i915 display-ID: :0 screens: 1
  Screen-1: 0 s-res: 1600x900 s-dpi: 96
  Monitor-1: HDMI-1 mapped: HDMI-A-1 model: Samsung res: 1600x900 dpi: 38 diag: 1388mm (54.6")
  OpenGL: renderer: Mesa Intel HD Graphics 4000 (IVB GT2) v: 4.2 Mesa 22.0.5 compat-v: 3.1
    direct render: Yes
```

**Issue**

The extension "Desktop Scroller" (desktop-scroller@ccadeptic23) does not work anymore.

What this extension does, is allows switch workspaces by moving the mouse pointer to the edge of the screen and switching workspaces back and forth by scrolling the mouse wheel.

After upgrading to LM 21 and Cinnamon 5.4.9, the extension does not work as expected anymore:

**Details**

I use 4 workspaces.
After the upgrade, the extension now only switches to the 2nd workspace.
Turning the mouse wheel again in the same direction reloads/switches to the 2nd workspace (again), but does not switch to the 3rd one.

I can switch back to workspace # 1 and forth to workspace # 2, but not to # 3 (or # 4).

Note:
Switching workspaces by other means works fine:
- using ctrl + alt + arrow keys works, I'm able to switch to # 2, # 3, and # 4 (back and forth).
- using the workspace overview "Show all workspaces" works as well

This is the function that does the switch:

```
	switch_workspace: function (direction) {

		let active = global.screen.get_active_workspace();
		let neighbor = active.get_neighbor(direction);

		if (active != neighbor) {

			if (this.showDirectionArrow)
				this.showDirection(direction);
			neighbor.activate(global.get_current_time());

		}

	}

```

Either:
- `global.screen.get_active_workspace()` does not return the active workspace (should return workspace # 2)
Or: 
- `active.get_neighbor(direction)` does not return the next workspace, (should return workspace # 3)

**Steps to reproduce**

Downloading "Desktop Scroller" (desktop-scroller@ccadeptic23) extension and using it.

**Expected behaviour**

To switch / cycle between all workspaces, not just the 1st and 2nd.
