### ISSUE TITLE
Major regression - Cinnamon dconf-config editor

### ISSUE THREAD

**Issue by noreasternhumidity** [linuxmint/cinnamon#11031]
```
System:
  Host: laptop Kernel: 5.10.0-16-amd64 x86_64 bits: 64 compiler: gcc 
  v: 10.2.1 Desktop: Cinnamon 5.4.9 tk: GTK 3.24.24 wm: Mutter 
  dm: LightDM 1.26.0 Distro: LMDE 5 Elsie base: Debian 11.2 bullseye 

Graphics:
  Device-1: Intel 2nd Generation Core Processor Family Integrated Graphics 
  vendor: Dell driver: i915 v: kernel bus ID: 00:02.0 chip ID: 8086:0126 
  class ID: 0300 
  Display: x11 server: X.Org 1.20.11 driver: loaded: modesetting 
  unloaded: fbdev,vesa resolution: 1600x900~60Hz s-dpi: 96 
  OpenGL: renderer: Mesa DRI Intel HD Graphics 3000 (SNB GT2) 
  v: 3.3 Mesa 20.3.5 compat-v: 3.0 direct render: Yes 

 ```

dconf-editor for /org/cinnamon/placement-mode has been removed (!!)

In other words, terminal and other windows now appear at the LEFT side of monitor.  They should appear at the CENTER of monitor.  Dconf-editor warns me that no schema can be found for this key, and offers to delete it.

**Steps to reproduce**

Open terminal.

**Expected behaviour**

Terminal should appear in CENTER of screen.
