### ISSUE TITLE
Resizing two "sticky" windows works incorrectly

### ISSUE THREAD

**Issue by spamegg1** [linuxmint/cinnamon#11169]
* Cinnamon version - 5.4.12
 * Distribution - Mint 21 
 * Graphics hardware *and* driver used
```
 ➜ inxi -G
Graphics:
  Device-1: AMD Picasso/Raven 2 [Radeon Vega Series / Radeon Mobile Series]
    driver: amdgpu v: kernel
  Display: x11 server: X.Org v: 1.21.1.3 driver: X: loaded: amdgpu,ati
    unloaded: fbdev,modesetting,vesa gpu: amdgpu resolution: 1920x1080~60Hz
  OpenGL: renderer: AMD Radeon Vega 11 Graphics (raven LLVM 13.0.1 DRM 3.42
  5.15.0-47-generic)
    v: 4.6 Mesa 22.0.5
```
 * 64 bit

### Issue
Horizontally resizing two half-screen windows that are opened side-by-side results in the right window vertically shrinking by itself.

### Steps to reproduce
1. Login to Guest account
2. Open a Nemo window with Super+E
3. Tile it to the left with Super+Left arrow
4. Open a Nemo window with Super+E
5. Tile it to the right with Super+Right arrow
6. Click and drag the mouse left-to-right on the separator between the two windows.
7. See issue. Here's a video:
[cinnamon-2022-09-15T092541+0300.webm](https://user-images.githubusercontent.com/4255997/190332059-785efc76-f125-400a-b61d-ad5daf917ea5.webm)

Notice that at the end of the video, the right window (which has now shrunk vertically) does not have a "resize cursor" at the bottom edge of it. So the window still "thinks" that it is vertically maximized.

### Expected behaviour
Resizing horizontally should not shrink the window vertically.
