### ISSUE TITLE
Random wifi disconnect and bluetooth disabled (random airplane mode)

### ISSUE THREAD

**Issue by VoldemortsCupcakeBakery** [linuxmint/cinnamon#11938]
### Distribution

Linux Mint 21.2 x86_64 (Linux Mint Edge)

### Package version

Cinnamon 5.8.4

### Graphics hardware in use

AMD Ryzen 5 7530U with Radeon Graphics (AMD Barcelo)

### Frequency

Quite often

### Bug description

Several times during the day, the wifi disconnects and also Bluetooth is disabled without me prompting the PC to do so. Hitting the airplane button (F11) after that ends the airplane mode and operation goes back to normal.

I attached what dmesg gives me when the disconnect happens. Mind that the button mentioned was not pressed by me. Mint also seems to have trouble with the driver for the wifi adapter (rtw89_8852ce) as suggested by the error in the log.

[rtwlog2.txt](https://github.com/linuxmint/cinnamon/files/13424995/rtwlog2.txt)

### Steps to reproduce

Put the above mentioned version of Linux Mint Edge on an HP Pro x360 435 13.3 inch G10 Notebook and use the system for a while. The wifi adapter seems to be newish as I had to install Edge to get it working. I did not fiddle with drivers or their configs, with Edge the wifi just worked out of the box.

inxi -Fxxxrz gives me:
```
Network:
  Device-1: Realtek vendor: Hewlett-Packard driver: rtw89_8852ce v: kernel
    pcie: speed: 5 GT/s lanes: 1 port: 2000 bus-ID: 01:00.0 chip-ID: 10ec:c852
    class-ID: 0280
  IF: wlp1s0 state: up mac: <filter>
```

### Expected behavior

No random airplane mode
