### ISSUE TITLE
Firefox profile that's "set as default" gets "excluded" from Alt-Tab switching after opening links from another app (Thunderbird, CherryTree)

### ISSUE THREAD

**Issue by firepainting** [linuxmint/Cinnamon#12475]
### Distribution

Mint 21.3

### Package version

6.0.4

### Graphics hardware in use

Please see _Additional information_ below.

### Frequency

Quite often

### Bug description

Launching links on the "set as default" Firefox profile, from another app (Thunderbird, Cherrytree), gets that specific Firefox window "excluded" from Alt-Tab switching.

### Steps to reproduce

I switch between 2 Firefox profiles (set either as default in about:profiles). Bug happens with either of them.

1. On Thunderbird or CherryTree, I click any link and it opens on the default Firefox profile. This is one tab open for now. Alt-Tab switching is fine.
2. The second opened link (again from Thunderbird or CherryTree) opens on the second tab of the same Firefox window above. This is where the bug happens.

Let's say I'm still on the Firefox window (on the second opened tab), and let's say the link was launched from Thunderbird. Upon pressing Alt-Tab I switch back to Thunderbird. 

However, upon pressing Alt-Tab again I do NOT return to the Firefox window anymore. Instead, I switch to the third app/window/etc. that's in the "queue" of my "switcher." The only way to go back to the Firefox window is to Alt+Tab, hold Alt, and click it with the mouse.

![alt_tab](https://github.com/user-attachments/assets/6acff601-483e-4c0b-a234-cc3563f924f9)

In the above screenshot, even if I came from the default Profile 1 (left-most end), upon Alt-Tabbing I would then switch between the second app (Firefox Profile 2) and the third app (gThumb).

Note: This happens only for the default profile. It happened once that I had 2 windows of the default profile and both of them got "excluded," both of them got stuck at the left-most end, next to each other. Alt+Tab here would now work for the third and fourth app/window in the queue.

### Expected behavior

Normal Alt-Tab behavior.

### Additional information

This happens on my two PCs.

PC 1:
```
Graphics:
  Device-1: Intel Xeon E3-1200 v3/4th Gen Core Processor Integrated Graphics 
  vendor: Micro-Star MSI driver: i915 v: kernel bus ID: 00:02.0 
  Display: x11 server: X.Org 1.20.9 driver: modesetting unloaded: fbdev,vesa 
  resolution: 1366x768~60Hz 
  OpenGL: renderer: Mesa DRI Intel HD Graphics 4600 (HSW GT2) 
  v: 4.5 Mesa 20.2.6 direct render: Yes 
```

PC 2:
```
Graphics:  
  Device-1: Intel HD Graphics 620 vendor: Lenovo driver: i915 v: kernel bus ID: 00:02.0 
  Display: x11 server: X.Org 1.19.6 driver: modesetting unloaded: fbdev,vesa
  resolution: 1366x768~60Hz 
  OpenGL: renderer: Mesa DRI Intel HD Graphics 620 (KBL GT2) 
  v: 4.6 Mesa 20.0.8 direct render: Yes 
```
