### ISSUE TITLE
Text on bright backgrounds with the default theme is hard to read

### ISSUE THREAD

**Issue by SpeeQz1** [linuxmint/cinnamon#12603]
### Distribution

Mint 22

### Package version

Cinnamon 6.2.9

### Graphics hardware in use

NVIDIA GeForce RTX 4060 Ti

### Frequency

Always

### Bug description

When using a very bright background fonts are very unreadable and require shadows to be read properly.
This is quite hurtful to the regular user experience so a solution to fix it would greatly benefit the regular user.

### Steps to reproduce

Create a folder or put some other file on the desktop and put it in a very brightly lit area of your screen usually on a bright background wallpaper.

### Expected behavior

Fonts are clearly readable or at the very least can be read.

### Additional information

![image](https://github.com/user-attachments/assets/a034b818-2163-49fe-b818-eb9a7bdf0a7d)

Personally I use text shadows in `~/.config/gtk-3.0/gtk.css` to fix this issue but adaptive font colors based on background brightness would be a welcome change too.

`gtk.css`:
```css
.nemo-desktop.nemo-canvas-item {
    color: #fff;
    text-shadow: 0px 0px 1px rgba(0, 0, 0, 1),
                 0px 0px 2px rgba(0, 0, 0, 1),
                 0px 0px 2px rgba(0, 0, 0, 1),
                 0px 0px 3px rgba(0, 0, 0, 1);
}

.nemo-desktop.nemo-canvas-item:selected {
    color: #fff;
    text-shadow: 1px 1px 3px rgba(0, 0, 0, 0.85);
    box-shadow: none;
}

.nemo-desktop.nemo-canvas-item:hover {
    text-shadow: 1px 1px 0px rgba(0, 0, 0, 0.85);
}
```
![image](https://github.com/user-attachments/assets/0f975ba2-0aa0-4c5f-8f78-ee84837c3a8a)
