### ISSUE TITLE
Monitors fail to initialize properly during boot

### ISSUE THREAD

**Issue by 2-bit-pixel** [linuxmint/cinnamon#12689]
### Distribution

Mint 22.1

### Package version

6.4.6

### Graphics hardware in use

Nvidia RTX 3080

### Frequency

Always

### Bug description

On restart, 3 monitors fail to initialize and flash on and off.  To correct the issue, I disconnect the bottom left monitor, allowing the top left and top right monitors to stabilize.  Once the top monitors are stabilized I plug in the bottom left and everything works normally.

```
Graphics:
  Device-1: NVIDIA GA102 [GeForce RTX 3080 Lite Hash Rate] vendor: eVga.com.
    driver: nvidia v: 550.120 arch: Ampere pcie: speed: 2.5 GT/s lanes: 16``
    ports: active: none off: DP-4,DP-5,HDMI-A-2 empty: DP-6 bus-ID: 01:00.0
    chip-ID: 10de:2216 class-ID: 0300
  Device-2: AMD vendor: ASRock driver: amdgpu v: kernel pcie: speed: 16 GT/s
    lanes: 16 ports: active: none empty: DP-1, DP-2, DP-3, HDMI-A-1, Writeback-1
    bus-ID: e2:00.0 chip-ID: 1002:13c0 class-ID: 0300 temp: 55.0 C
  Display: x11 server: X.Org v: 21.1.11 with: Xwayland v: 23.2.6 driver: X:
    loaded: amdgpu,nouveau unloaded: fbdev,modesetting,vesa failed: nvidia
    dri: radeonsi gpu: nvidia,nvidia-nvswitch display-ID: :0 screens: 1
  Screen-1: 0 s-res: 5120x2880 s-dpi: 96 s-size: 1355x762mm (53.35x30.00")
    s-diag: 1555mm (61.2")
  Monitor-1: DP-0 pos: bottom-l res: 2560x1440 hz: 60 dpi: 93
    size: 698x392mm (27.48x15.43") diag: 801mm (31.52") modes: N/A
  Monitor-2: DP-2 pos: top-left res: 2560x1440 hz: 60 dpi: 93
    size: 698x392mm (27.48x15.43") diag: 801mm (31.52") modes: N/A
  Monitor-3: HDMI-0 pos: primary,top-right res: 2560x1440 hz: 120 dpi: 35
    size: 1872x1053mm (73.7x41.46") diag: 2148mm (84.56") modes: N/A
  API: EGL v: 1.5 hw: drv: nvidia drv: amd radeonsi platforms: device: 0
    drv: nvidia device: 2 drv: radeonsi device: 3 drv: swrast gbm:
    drv: kms_swrast surfaceless: drv: nvidia x11: drv: nvidia
    inactive: wayland,device-1
  API: OpenGL v: 4.6.0 compat-v: 4.5 vendor: nvidia mesa v: 550.120
    glx-v: 1.4 direct-render: yes renderer: NVIDIA GeForce RTX 3080/PCIe/SSE2
```

In Display Manager, the monitors are labeled:

2   |   1
3

However the monitors are actually recognized as:

2  |  3
1

This configuration matches:

```
Monitor-1: DP-0 pos: bottom-l res: 2560x1440 hz: 60 dpi: 93
    size: 698x392mm (27.48x15.43") diag: 801mm (31.52") modes: N/A
  Monitor-2: DP-2 pos: top-left res: 2560x1440 hz: 60 dpi: 93
    size: 698x392mm (27.48x15.43") diag: 801mm (31.52") modes: N/A
  Monitor-3: HDMI-0 pos: primary,top-right res: 2560x1440 hz: 120 dpi: 35
    size: 1872x1053mm (73.7x41.46") diag: 2148mm (84.56") modes: N/A
```

Also note that Monitor-1 (bottom-l) is not correctly recognized and should be recognized as Monitor-2 as per Nvidia spec that the first port used displays the UEFI and this cannot be changed.  The order that the monitors are plugged in to the GPU would make the correct order as Monitor-1 top left, Monitor-2 bottom left, Monitor-3 top right.

I tried reverting to a previous kernel, no change, and adding the below line to GRUB, also with no change:

`BOOT_IMAGE=/boot/vmlinuz-6.8.0-51-generic root=UUID=bf7a041e-cada-4670-bcce-5147614228aa ro nvidia_drm.fbdev=1`

This is a new problem.  This configuration was the same under Mint 22, and after upgrading to 22.1, things worked for a few days until the problem started.  There have been no recent changes to hardware or software proceeding the problem.

### Steps to reproduce

Reboot.  PC is dual boot, problem is not present in Windows, only Mint.

### Expected behavior

All three monitors should initialize and display correctly after boot instead of flashing on and off.

### Additional information

![Image](https://github.com/user-attachments/assets/a7f4b8c8-35e6-415a-b090-2dd62b2774a4)
