### ISSUE TITLE
Theme: .panel-top -> border-bottom property not functioning correctly...

### ISSUE THREAD

**Issue by Xethron** [linuxmint/Cinnamon#1375]
I'm writing a theme. I tried to set bottom border using the following, but it doesn't work.

``` css
.panel-top {
    border-bottom: 1px solid rgba(59,181,229,0.4);
}
```

Setting the border property does however set a bottom border as well as top, left and right.

``` css
.panel-top {
    border: 1px solid rgba(59,181,229,0.4);
}
```

Setting border-bottom to none after setting border, does remove the bottom border. So the bottom-border property is identified to some extent.

``` css
.panel-top {
    border: 1px solid rgba(59,181,229,0.4);
    border-bottom: none;
}
```

Currently I'm using the following workaround to set the bottom border.

``` css
.panel-top {
    border: 1px solid rgba(59,181,229,0.4);
    border-left: none;
    border-right: none;
    border-top: none;
}
```

Thanks,
Xethron
