### ISSUE TITLE
Increase size of callendar applet window.

### ISSUE THREAD

**Issue by alxgvr** [linuxmint/Cinnamon#5431]
One thing I realy don`t like about cinnamon calendar - it is VERY tiny. 
Too smal for PC screen. 

I think dates window should be increased in size.

**Comment by Vahan86** [comment]
+1 for proposal.

**Comment by Cos-mo** [comment]
Question is: How big?

My screen has a resolution of 1920 x 1080, the calendar displays with 300 x 350 pixel. Not only is it enough IMHO, I would not want to have it bigger.

**Comment by alxgvr** [comment]
1.5x Larger.
Just look at Windows 10 calendar, how big it is.

2016-10-01 1:35 GMT+03:00 Cos-mo <notifications@github.com>:

**Comment by Cos-mo** [comment]
>  Just look at Windows 10 calendar, how big it is. 

I cannot, no Windows here.

IMHO: 1.5 x larger is too large.
So -1 from me.

**Comment by Topperfalkon** [comment]
I'm not overly fussed about making the calendar bigger, but I must say that the Windows 10 calendar does open up to a decent size, and I wouldn't mind similar in Mint

**Comment by Odyseus** [comment]
Hello, g@ys.

@alxgvr, @Topperfalkon: The calendar size is defined by the cinnamon theme that you are using. The following css code placed at the end of the **cinnamon.css** file found in your theme folder will do the trick:

```css
.calendar,
.datemenu-date-label,
.calendar-month-label,
.calendar-change-month-back,
.calendar-change-month-forward,
.calendar-day-base,
.calendar-day-base,
.calendar-day-heading,
.calendar-week-number,
.calendar-day,
.calendar-day-top,
.calendar-day-left,
.calendar-work-day,
.calendar-nonwork-day,
.calendar-today,
.calendar-other-month-day {
	font-size: 1.5em;
}
```
