### ISSUE TITLE
All dialogues now bordered regardless of theme.

### ISSUE THREAD

**Issue by azariah001** [linuxmint/Cinnamon#5921]
So I'm on Antergos Arch running Cinnamon 3.2.1 and ever since yesterday, when I updated Cinnamon to 3.2.0, all of the panel dialogues regardless of whether it's the Menu, Calendar, Network, Sound, etc. have this border around them. Pre-update this wasn't there and I don't want it there, I've tested this by changing my theme to the default 'cinnamon' theme and a couple of others and the borders persists completely unchanged by any of the themes.

Why? Please fix, it's an eyesore.

Screenshots:
![screenshot from 2016-11-09 11-38-12](https://cloud.githubusercontent.com/assets/5634872/20124359/908cb9a6-a671-11e6-81ef-927392228363.png)
![screenshot from 2016-11-09 11-38-15](https://cloud.githubusercontent.com/assets/5634872/20124358/908c3076-a671-11e6-876b-cb0a272abfe7.png)

**Comment by Odyseus** [comment]
Hello, @azariah001.

This isn't a Cinnamon issue. Cinnamon 3.2.x uses a new class for menus (menu). All themes need to be updated to reflect this change.

In the mean time, you can edit your themes by adding something like the following to the cinnamon.css file of your theme:

```css
.menu {
	border: none;
}
```

Depending on the theme, the changes will be more or less complex.

**Comment by azariah001** [comment]
Ok thanks for the reply but I still question why `border: none;` isn't the default, if only for the sake of reducing the impact of this change. Because currently, it's a breaking change that's going to cause issues across every single existing theme, some of which may not have an active developer behind them currently.

Now that I'm aware I'm going to be sure to assist with changes to the theme I'm using but yeah the decision for the default value still bugs me. And this isn't the only change either, just noticed that the font color declarations aren't working as expected either. I guess this is what I get for living on the cutting edge. :stuck_out_tongue_closed_eyes:

**Comment by Odyseus** [comment]
Well, I just suggested you `border: none;` because you said you wanted to get rid of the border. But the vast majority of Cinnamon themes uses some kind of styling for their borders on menus. And using `border: none;` by default would have been even more horrendous in my opinion. LOL

This is what I did to make my Mint-X based themes to set the correct appearance to all Cinnamon menus.

Original CSS **not** compatible with Cinnamon 3.2:

```css
.popup-menu-boxpointer {
    -arrow-border-radius: 4px;
    -arrow-background-color: #ececec;
    -arrow-border-width: 1px;
    -arrow-border-color: rgba(40, 40, 40, 0.3);
    -arrow-base: 18px;
    -arrow-rise: 10px;
    -st-shadow: 0px -1px 2px 0px rgba(255, 255, 255, 0.9);
    -boxpointer-gap: 2px;
}

.popup-menu {
    color: rgb(70, 70, 70);
    min-width: 100px;
}

.popup-menu StEntry {
    /* CSS */
}

.popup-menu StEntry:focus {
    /* CSS */
}
```


CSS compatible with Cinnamon 3.2:

```css
.popup-menu-boxpointer {
    -/* CSS left untouched for retro-compatibility */
}

.popup-menu {
    -/* CSS left untouched for retro-compatibility */
}

.menu {
    border-radius: 4px;
    background-color: #ececec;
    border-width: 1px !important;
    border-color: rgba(40, 40, 40, 0.3);
    color: rgb(70, 70, 70);
    font-size: 9.5pt;
    min-width: 100px;
}

.menu StEntry,
.popup-menu StEntry {
    /* CSS */
}

.menu StEntry:focus,
.popup-menu StEntry:focus {
    /* CSS */
}
```

As you can see, it wasn't that complicated. I just *merged* the styles of two unused classes (**popup-menu-boxpointer** and **popup-menu**) into the **menu** class and I also added the **menu StEntry** selector so it can also modify the search boxes.

I could assist you further, but first you should close this issue.
