### ISSUE TITLE
Undefined -gradient-end/-gradient-start outputs lots of warnings

### ISSUE THREAD

**Issue by germanfr** [linuxmint/Cinnamon#6034]
Cinnamon outputs lots of warnings to `~/.xsession-errors` each time you open a popup menu if the themer hasn't defined these properties for `popup-separator-menu-item`.
``` scss
.popup-separator-menu-item {
    -gradient-start: #000000;
    -gradient-end: #000000;
}
```

I'm not sure what they are for. They don't seem to affect the separator in any way. They are weird and most likely themers won't use them. It would be great if they were ignored like any other CSS property when not defined, instead of writing all these warnings.

These are the warning messages printed for just one popup menu opened:
```
(cinnamon:16343): St-WARNING **: Did not find color property '-gradient-start'

(cinnamon:16343): St-WARNING **: Did not find color property '-gradient-end'

(cinnamon:16343): St-WARNING **: Did not find color property '-gradient-start'

(cinnamon:16343): St-WARNING **: Did not find color property '-gradient-end'

(cinnamon:16343): St-WARNING **: Did not find color property '-gradient-start'

(cinnamon:16343): St-WARNING **: Did not find color property '-gradient-end'

(cinnamon:16343): St-WARNING **: Did not find color property '-gradient-start'

(cinnamon:16343): St-WARNING **: Did not find color property '-gradient-end'

(cinnamon:16343): St-WARNING **: Did not find color property '-gradient-start'

(cinnamon:16343): St-WARNING **: Did not find color property '-gradient-end'

(cinnamon:16343): St-WARNING **: Did not find color property '-gradient-start'

(cinnamon:16343): St-WARNING **: Did not find color property '-gradient-end'
```

**Comment by JosephMcc** [comment]
> They are weird and most likely themers won't use them.

What? Are you calling themers lazy? ;)

To be serious, the separator needs those values to draw properly. I think sending a warning when it can't find them is perfectly valid. We try to keep the default cinnamon.css up to date so it can be used as reference for what a theme needs to contain.

**Comment by Odyseus** [comment]
Hello, everybody.

I have been struggling to get rid of those warnings since I started using Cinnamon. Without this issue opened by @germanfr, I would never have guessed how to fix it in a million years. Thanks, **germanfr**.

@JosephMcc
While investigating how to *fix* these warnings, I tracked down the warning message to the **st_theme_node_get_color** function inside the **[st-theme-node.c](https://github.com/linuxmint/Cinnamon/blob/master/src/st/st-theme-node.c)** file. Would it be possible for that message to also include the element that triggers the warning? That way, we could know exactly where to look at or at least have a hint.

One last question. I'm thinking of creating a pull request for the [Mint-X themes](https://github.com/linuxmint/cinnamon-themes) because these themes doesn't have those properties defined for the **popup-separator-menu-item** class and also trigger those warnings.

```css
.popup-separator-menu-item {
    background-color: rgb(210, 210, 210);
    height: 1px;
}
```

Would the following change be correct?
```css
.popup-separator-menu-item {
    background-color: rgb(210, 210, 210);
    -gradient-start: transparent;
    -gradient-end: transparent;
    height: 1px;
}
```

O should I simply replace the **background-color** property like this?
```css
.popup-separator-menu-item {
    -gradient-start: rgb(210, 210, 210);
    -gradient-end: rgb(210, 210, 210);
    height: 1px;
}
```

**Comment by germanfr** [comment]
I still don't know what are they used for. When I apply them there's no any visible effect on the separator.

They define colors so I imagine it must be something background related. If they are not defined they could be simply not painted, the same as if you don't define the background it paints as transparent(?)

@Odyseus if you remove the background property they become transparent. They are not equivalent, I think.

**Comment by Odyseus** [comment]
@germanfr.
Ops! You are right. I have two virtual machines opened and I mixed the results of the tweaks that I did to my themes. I will edit my previous message.

**Comment by JosephMcc** [comment]
The separator uses several properties to draw. Like I said you can look at the default theme: https://github.com/linuxmint/Cinnamon/blob/master/data/theme/cinnamon.css#L193

Setting both gradients to the same color should work but you need to set the height property as well.

**Comment by Odyseus** [comment]
Thanks, @JosephMcc.

I went ahead and also added the **-margin-horizontal** property just in case:
```css
.popup-separator-menu-item {
    -gradient-height: 1px;
    -gradient-start: rgb(210, 210, 210);
    -gradient-end: rgb(210, 210, 210);
    -margin-horizontal: 0;
    height: 1px;
}
```

And now I think that I understand perfectly why those *"CSS properties"* need to be defined even if they aren't really used by the theme. By looking at the [popupMenu.js](https://github.com/linuxmint/Cinnamon/blob/master/js/ui/popupMenu.js#L507) and [separator.js](https://github.com/linuxmint/Cinnamon/blob/master/js/ui/separator.js#L21) files, everything became clear to me.
