### ISSUE TITLE
Distorted applet "keyboard@cinnamon.org" in the vertical panel

### ISSUE THREAD

**Issue by andreevlex** [linuxmint/cinnamon#6101]
OS - Linux Mint 18.1
Desktop - Cinnamon 3.2.6

When enabled in the settings option "Allow Cinnamon to scale panel text and icons according to the panel width"
Setting the largest value of the length of panel in the settings leads to a distortion of the applet "keyboard@cinnamon.org"
![keyb_mint18_1](https://cloud.githubusercontent.com/assets/20382553/21287886/c63b42ee-c48e-11e6-9b9a-f61583c179e1.png)

**Comment by zagortenay333** [comment]
Setting this fixes it for horizontal panels completely and somewhat decently for vertical panels:

```css
.panel-status-button {
    height: inherit;
}

.panel-top    .panel-status-button,
.panel-bottom .panel-status-button {
    height: 1.8em;
}
```
