### ISSUE TITLE
OSD level bar overflow

### ISSUE THREAD

**Issue by germanfr** [linuxmint/Cinnamon#6616]
When you apply a **border** or a **padding** to the `level` class in a theme it doesn't limit the max width.
Also when you apply a **margin** to the `level-bar` class.

![screenshot from 2017-06-15 11-49-40](https://user-images.githubusercontent.com/10391266/27175958-227ddf02-51c1-11e7-834f-71c32d144b11.png)

Tested on the "Linux Mint" theme. Just add this:
```css
.osd-window .level {
    border: 1px solid red;
    /* Or this: */
    /* padding: 1px; */
}
```
