### ISSUE TITLE
Ugly visual artifact when opening specific settings

### ISSUE THREAD

**Issue by memeplex** [linuxmint/cinnamon#7720]
```
~:: cinnamon --version
Cinnamon 3.8.6
~:: uname -a
Linux carlos 4.14.53-1-MANJARO #1 SMP PREEMPT Tue Jul 3 17:59:17 UTC 2018 x86_64 GNU/Linux
~:: lspci | grep VGA
00:02.0 VGA compatible controller: Intel Corporation 2nd Generation Core Processor Family Integrated Graphics Controller (rev 09)
~:: pacman -Qs video intel
local/xf86-video-intel 1:2.99.917+829+gd7dfab62-1 (xorg-drivers)
    X.org Intel i810/i830/i915/945G/G965+ video drivers
 ```

When opening specific settings (for example Network or Keyboard) first the full Control Center is displayed and immediately after that replaced by the requested settings screen. The transition is clearly perceptible and looks ugly, specially when settings are called from an applet (for example the Network applet; here, since there seems to be no relationship between the Control Center and a list of available networks, the artifact comes as most unpleasant).

**Comment by smurphos** [comment]
I can reproduce this on similar hardware on Mint 19 - 

```
System:
  Host: HP-Pavilion-g6-Notebook-PC Kernel: 4.15.0-24-generic x86_64 bits: 64 
  compiler: gcc v: 7.3.0 Desktop: Cinnamon 3.8.7 Distro: Linux Mint 19 Tara 
  base: Ubuntu 18.04 LTS Bionic 

Graphics:
  Card-1: Intel 2nd Generation Core Processor Family Integrated Graphics 
  driver: i915 v: kernel bus ID: 00:02.0 
  Display: x11 server: X.Org 1.19.6 driver: modesetting unloaded: fbdev,vesa 
  resolution: 1366x768~60Hz 
  OpenGL: renderer: Mesa DRI Intel Sandybridge Mobile v: 3.3 Mesa 18.0.5 
  direct render: Yes
```
