### ISSUE TITLE
Grouped Window List: border on active window not needed, if button label is shown

### ISSUE THREAD

**Issue by sphh** [linuxmint/Cinnamon#8186]
```
 * Cinnamon version (cinnamon --version): Cinnamon 4.0.8
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...): Mint 19.1
 * Icon Theme: Cinnamon Mint-Y
 * Desktop Theme: Cinnamon Mint-Y-Dark
 ```

**Issue**

The new Grouped Window List marks **all** opened windows with a green bar, independent if the window is pinned or not:
![image](https://user-images.githubusercontent.com/4856462/50347628-82a90a80-0536-11e9-939c-edcf008321c4.png)

This is perfectly ok, if no titles are shown. In the screenshot above, Firefox, the terminal and Nemo are all pinned applications, but only Firefox and the terminal are having a window. I now know that these are open.

If I enable the `Button label`, GWL shows as follows:
![image](https://user-images.githubusercontent.com/4856462/50347603-6016f180-0536-11e9-9da2-0adba811b670.png)

GWL again marks all open windows by a green border, but I do know that these windows are open (compared to just pinned), because they show a window title.

**Steps to reproduce**

Pin some applications in GWL and change the setting `Button label` from `None` to e.g. `Window title`.

**Expected behaviour**

IMHO there is no need to show the green border for open windows if a button label is displayed. It just distracts me. I can see the reason to mark the currently active window so that it stands out. I would wish if I could disable this green bar. Maybe making it optional would be an option.

**Other information**

I believe #8102 is related to this feature request.

What what would be the identifier of these opened windows, so that I can change it myself in the stylesheet?

**Comment by jaszhix** [comment]
This is determined by the theme, and not really a GWL issue. In Mint Y, you could try changing `border-color` to `rgba(0, 0, 0, 0)` on the `grouped-window-list-item-box` class pseudo selectors.

**Comment by sphh** [comment]
Thanks. In `/usr/share/themes/Mint-Y/cinnamon/cinnamon.css` I changed
```css
.grouped-window-list-item-box:active, .grouped-window-list-item-box:checked {
   color: #ffffff;
   border-color: #9ab87c; }
```
to
```css
.grouped-window-list-item-box:active, .grouped-window-list-item-box:checked {
   color: #ffffff;
   border-color: rgba(0, 0, 0, 0); }
```
and restarted Cinnamon, but that did not help.

I also tried to add
```css
.grouped-window-list-item-box:running {
   border-color: rgba(0, 0, 0, 0); }
```
This also does not have the effect of removing the borders.

What pseudo classes do I have to use? Is this the right file where to make the changes: `/usr/share/themes/Mint-Y/cinnamon/cinnamon.css`?

**Comment by sphh** [comment]
Well, I use these them settings:
![image](https://user-images.githubusercontent.com/4856462/50426788-650dd500-0897-11e9-8b55-e1eb91aff6b4.png)
and I edited the file `/usr/share/themes/Mint-Y/cinnamon/cinnamon.css` and tried the file `/usr/share/themes/Mint-Y-Dark/cinnamon/cinnamon.css`. No luck with either of them.

Which file do I have to edit??

**Comment by jaszhix** [comment]
Check ~/.xsession-errors.

```Cjs-Message: 17:25:50.703: JS LOG: [LookingGlass/info] loading user theme: /usr/share/themes/Mint-Y-Dark-Aqua/cinnamon/cinnamon.css```

**Comment by sphh** [comment]
Thanks. `cat .xsession-errors | grep theme` revealed that I edited the right file. I finally managed to get it working:

I had to delete (or comment out) this part:
```css
  .grouped-window-list-item-box:active, .grouped-window-list-item-box:checked {
    color: #ffffff;
    border-color: #8fa876; }
```
and I added this instead:
```css
  .grouped-window-list-item-box:focus {
    color: #ffffff;
    background-color: rgba(255, 255, 255, 0.3);
    border-color: #8fa876; }
```
