### ISSUE TITLE
[Feature request] Grouped Window List - Customize the "indicator" of opened windows

### ISSUE THREAD

**Issue by Zeustopher** [linuxmint/cinnamon#8296]
``` 
* Cinnamon version (cinnamon --version): Cinnamon 4.0.9
* Distribution - (Mint 17.2, Arch, Fedora 25, etc...): Mint 19.1
* Icon Theme: Cinnamon Mint-Y-Aqua
* Desktop Theme: Cinnamon Mint-Y-Dark-Aqua
```

I use Linux Mint 19.1 _(LOVE IT!)_ and enjoy the new Grouped Window List. However, I use a 4k, 40" monitor and a standing desk. Because of the viewing angle I am at, I can't at all see the little "indicator lines" at the bottom of the icons of there being an open window of that app already.

I'd like to be able to customize the position, thickness, etc. of those indicator lines. I imagine that option possibly being a good place in the "Panel" settings for the Grouped Window List Settings.

From reading around I found that this appears to actually potentially be an aspect of the theme I am using. I manually changed the CSS of the `cinnamon.css` for the theme I am using from
```css
.grouped-window-list-item-box.top, .grouped-window-list-item-box.bottom {
    border-bottom-width: 2px; }
```
to
```css
.grouped-window-list-item-box.top, .grouped-window-list-item-box.bottom {
    border-bottom-width: 5px; }
```
and that made it thick enough I could then easily see the indicators under the icons. See below screenshots.

Before 2px-5px change:
![image](https://user-images.githubusercontent.com/11470532/51128662-ae41ac80-17e5-11e9-92ef-92b1e01ef4bc.png)

After 2px-5px change:
![image](https://user-images.githubusercontent.com/11470532/51129301-586e0400-17e7-11e9-8539-85920ca10cb4.png)

I don't think this is a very high priority, but it would be nice to have the ability to customize those a little bit (maybe things like thickness, color, position [bottom, left, right, top, etc]).
