### ISSUE TITLE
st-shadows painted wrong

### ISSUE THREAD

**Issue by germanfr** [linuxmint/cinnamon#8651]
```
 * Cinnamon version: master (94afc73576eb1c0fedcc02ccc87583ee1e362cb9)
 * Distribution - Manjaro
 * Graphics hardware *and* driver used: Intel Corporation HD Graphics 530 - nvidia-driver-390.116-0ubuntu0.18.04.1
 * 64 bit
 * No errors in the log
 ```

**Issue**

Shadows of St nodes are incorrectly painted because:
 * The shadow is visible through semi-transparent backgrounds.
 * The shadow offset fill uses the alpha component of the background color instead of its own while the shadow edges use the correct alpha. This results in a weird blurred outline with transparent backgrounds.

![Screenshot from 2019-06-19 19-57-25](https://user-images.githubusercontent.com/10391266/59788883-087ef600-92cd-11e9-9a98-866abdb16c01.png)

**Steps to reproduce**

Add this piece of css at the end of your theme (I tested with the default one).

```css
.menu {
    background-color: rgba(80,80,80,0.25);
    box-shadow: 0px 0px 4px 32px #ff0000;
}
```

Adding a simple shadow to a menu with a semi-transparent white background results in a weird stain near the borders inside.
![Screenshot from 2019-06-19 20-11-04](https://user-images.githubusercontent.com/10391266/59789563-7546c000-92ce-11e9-9af9-ca6363e717e4.png)

```css
.menu {
    background-color: rgba(255,255,255,0.25);
    box-shadow: 0px 0px 6px #000000;
}
```

**Expected behaviour**

* Shadow offsets should be filled with the same opacity as the shadow border.
* Shadows should not be visible through transparent backgrounds.

**Other information**

I don't know since when this is happening or if it ever worked right.
