### ISSUE TITLE
Window preview stays after window closed

### ISSUE THREAD

**Issue by buzo-ffm** [linuxmint/cinnamon#9051]
```
 * Cinnamon 4.4.4
 * Distribution - Arch
 * Graphics hardware *and* driver used: Intel Corporation HD Graphics 620 (rev 02), intel
 * 64 bit
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog (not relevant)
 ```
**Issue**
Sometimes the panel shows a tooltip which does not vanish until Cinnamon is restarted.

**Steps to reproduce**
There are many ways to reproduce. Maybe the easiest one is:
* Open Nemo
* Hover over the Nemo entry in the panel until the tooltip (window preview) is visible.
* Press Ctrl+W to close Nemo.

**Expected behaviour**
The panel entry and the tooltip vanishes.

**Actual behaviour**
Only the panel entry is gone. The tooltip stays until I restart Cinnamon.

**Comment by Vahan86** [comment]
I'm not able to reproduce the issue, it seems to work correctly in Cinnamon 4.4.5 (Linux Mint 19.3)

**Comment by buzo-ffm** [comment]
Did you try to close the window via keyboard shortcut, too, while the window preview was visible?

Anyway, I'll wait till 4.4.5 lands in Arch then.

**Comment by tommypyatt** [comment]
I'm able to replicate what I think to be the same issue on 4.4.5:

```
Distro: Linux Mint 19.3 Tricia base: Ubuntu 18.04 bionic
Desktop: Cinnamon 4.4.5
Graphics:
Device-1: Intel 3rd Gen Core processor Graphics vendor: Lenovo 
  driver: i915 v: kernel bus ID: 00:02.0 chip ID: 8086:0166 
  Display: x11 server: X.Org 1.19.6 driver: modesetting unloaded: fbdev,vesa 
  resolution: 1600x900~60Hz
```

### Steps to replicate

1. Open any application and hover over panel icon:
![hover](https://user-images.githubusercontent.com/2505431/71416382-06209e80-2658-11ea-9627-e736830f6fb0.png)

2. Close application with F4 while hovering

3. Note tooltip will not disappear until logout:
![after-f4](https://user-images.githubusercontent.com/2505431/71416401-26e8f400-2658-11ea-90ce-a3f2f085592d.png)
