### ISSUE TITLE
Icons on vertical panel rearrange themselves whenever a window/app/prompt, which is represented by an icon, gets closed

### ISSUE THREAD

**Issue by firepainting** [linuxmint/cinnamon#9845]
* Cinnamon version - 4.8.5
 * Distribution - Mint 20.1 Ulyssa
 * Graphics hardware *and* driver used

```
Graphics:
  Device-1: Intel HD Graphics 620 vendor: Lenovo driver: i915 v: kernel 
  bus ID: 00:02.0 
  Display: x11 server: X.Org 1.20.9 driver: modesetting unloaded: fbdev,vesa 
  resolution: 1366x768~60Hz 
  OpenGL: renderer: Mesa Intel HD Graphics 620 (KBL GT2) v: 4.6 Mesa 20.2.6 
  direct render: Yes 

```

 * 64 bit
 * Attach ~/.xsession-errors, or /var/log/syslog
[XSession Errors.txt](https://github.com/linuxmint/cinnamon/files/5795328/XSession.Errors.txt)
[Sys Log.txt](https://github.com/linuxmint/cinnamon/files/5795329/Sys.Log.txt)
 
--

**Edit: This also happens on my other PC.** Same Cinnamon version and distribution as above. Also 64 bit.

```
Graphics:
  Device-1: Intel Xeon E3-1200 v3/4th Gen Core Processor Integrated Graphics 
  vendor: Micro-Star MSI driver: i915 v: kernel bus ID: 00:02.0 
  Display: x11 server: X.Org 1.20.9 driver: modesetting unloaded: fbdev,vesa 
  resolution: 1366x768~60Hz 
  OpenGL: renderer: Mesa DRI Intel HD Graphics 4600 (HSW GT2) 
  v: 4.5 Mesa 20.2.6 direct render: Yes 
```

--

**Issue**

Hello,

I just upgraded to 20.1 Ulyssa (from 20 Ulyana).

The icons on my vertical panel rearrange themselves whenever a window/app/prompt--which is represented by an icon--gets closed. The new arrangement seems set, it doesn't change thereafter.

I restored all settings to default: right-click on panel > Troubleshoot > Restore all settings to default... and it still behaves the same.

For example, this is how I regularly position my icons, more or less: 
![panel 1](https://user-images.githubusercontent.com/50393421/104173059-30e6bc00-5440-11eb-9c8b-8555293aa1c3.png)

After closing the file manager: 
![panel 2](https://user-images.githubusercontent.com/50393421/104173057-2fb58f00-5440-11eb-8d7a-1ea632f8d6e7.png)

I've been using Mint (Edit: Cinnamon) since 19.1 (April 2019) and this is the first time this happened.

**Steps to reproduce**

Arrange icons to desired positions, by dragging. Close any open window/app/prompt represented by an icon on the panel.

**Expected behaviour**
Icons' positions remain in previously set order.

**Other information**
N/A

**Configuration info, if applicable**
N/A

Thank you.
